#!/bin/bash
set -e
set -o pipefail

# add group
if ! getent group | grep -q "^fcore:" ; then
    echo "Creating system group: fcore"
    groupadd --system fcore
fi

# add user
if ! getent passwd | grep -q "^fcore:"; then
    echo "Creating fcore system user"
    useradd --gid "fcore" --system -m fcore
fi

# build nodejs addons
cd "/usr/opt/fcore"
SKIP_BITCOIN_DOWNLOAD=1 npm rebuild

# setup data directory
mkdir -p "/home/fcore/.fcore/data"
chown -R fcore:fcore "/home/fcore/.fcore"

# start fcore
if hash service 2> /dev/null; then
    service fcore start || echo "fcore could not be registered or started"
elif hash start 2> /dev/null; then
    start fcore || echo "fcore could not be registered or started"
elif hash systemctl 2> /dev/null; then
    {
        systemctl enable "fcore.service" && \
            systemctl start "fcore.service"
    } || echo "fcore could not be registered or started"
else
    echo 'Your system does not appear to use upstart or systemd, so fcore could not be started'
fi
